blank_issues_enabled: true
contact_links:
  - name: 报告安全漏洞
    url: https://docs.github.com/zh/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability
    about: 请不要在公开 Issue 中报告漏洞，使用仓库「Security」标签下的私密报告功能
